
name: Build Docker Image (no push)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image (no push)
        run: |
          docker build -t myappcar:test .
